### ISSUE TITLE
Hikvision Twoway Audio

### ISSUE THREAD

**Issue by Vignesh-AK** [koush/scrypted#1028]
Requesting assistance with integrating Two-way audio and streaming for a Hikvision Video Door Phone using Scrypted. Seeking guidance on the integration process and the required plugins I need to install on Scrypted . Grateful for any help provided. Thank you!

**Comment by VCTGomes** [comment]
You can just use Hikvision plugin and set up to use Hikvision protocol instead of Onvif, it may work on your intercom. However, you'll need an external way to catch button events and send to Scrypted, there's a various messages about how to do it on Discord from Scrypted. 

Beyond that, until now, it's impossible to use Two-way audio while doorbell is ringing (if someone press the button and you receive notification), you can check it better here: https://github.com/koush/scrypted/issues/533
