### ISSUE TITLE
Recording light on G3 Flex and G3 Instant is turned on after restarting Scrypted

### ISSUE THREAD

**Issue by Calimerorulez** [koush/scrypted#129]
In Unifi Protect, I've disabled the recording lights on my camera's. After updating/restarting Scrypted, the recording lights are enabled again in the camera settings, and are turned on.

This is the case for my G3 Flex and G3 Instant, but not for my G4 Instant.

**Comment by koush** [comment]
you can turn the recording light on an off now, in the web interface. maybe you did that on accident?

**Comment by Calimerorulez** [comment]
Hi,

I can't actually find it in the web interface, maybe it is the default setting there then?

**Comment by koush** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/73924/150187774-b33bd573-5c71-4159-a30c-3acade92e068.png">

**Comment by RobertDWhite** [comment]
Mine does this randomly since implementing Scrypted. The light will come on or off what appears to be randomly, but it may be associated with the camera randomly re-connecting to WiFi. Not sure, but I will be looking more into that. We currently have one in the nursery so it has been enough to bother that baby. Lol. Oh well

**Comment by koush** [comment]
I'll be disabling this. It's problematic.

**Comment by koush** [comment]
ok it's been made optional now.
