### ISSUE TITLE
Reolink Doorbell PoE 2-way audio not working since reolink:0.6.4 and later

### ISSUE THREAD

**Issue by hgregorian** [koush/scrypted#1405]
**Describe the bug**
Since updating to the reolink plugin 0.6.4 and subsequently 0.6.5, 2-way audio has ceased to function.  Rolling back to 0.6.3 allows for 2-way audio to function again.  Note that firmware on the doorbells is v3.0.0.2033_23041302 and not the latest firmware (v3.0.0.3215_2401262241). See this [issue](https://github.com/koush/scrypted/issues/1376) for details on newest doorbell firmware not working.

**To Reproduce**
1. Update reolink plugin to 0.6.4 or higher
2. Attempt 2-way audio
3. Observe that 2-way audio is non-functional
4. Install reolink plugin 0.6.3 to restore functionality

**Expected behavior**
2-way audio functions as it did with reolink plugin 0.6.3 and earlier

**Server (please complete the following information):**
 - OS: Debian 12
 - Installation Method: Home Assistant Add-On

**Hardware Model (please complete the following information):**
 - Device: Reolink Doorbell PoE (x2)

**Client (please complete the following information, if applicable):**
 - Software: Home app

**Comment by koush** [comment]
fixed

**Comment by hgregorian** [comment]
Thank you!

> fixed

**Comment by cena-scott** [comment]
I just got the new White version of Reolink doorbell POE, it comes pre-installed with firmware version v3.0.0.3215_2401272070, with hardware No. DB_566128M5MP_P_W. The W at the end of the hardware No refer to the White version.

I have the same issue, 2 way audio not working, I can hear from homekit but the speaker on the doorbell itself not activated, no blue LED turn on around the doorbell button, tried Reolink plugin and ONVIF, both not working, I can't install the older firmware from the Black version it gives error not recognized.

Any idea anyone can help please? I am thinking to return it since I still have time for return policy but before I return it I want to make sure it doesn't work on White version, I have seen many people says downgrade to older firmware on Black doorbell works, but can't do the same for the White version, I choose this white version because it has taller camera view 3:4 head-to-toe as they say.

**Comment by paolotremadio** [comment]
> I just got the new White version of Reolink doorbell POE, it comes pre-installed with firmware version v3.0.0.3215_2401272070, with hardware No. DB_566128M5MP_P_W. The W at the end of the hardware No refer to the White version.
> 
> I have the same issue, 2 way audio not working, I can hear from homekit but the speaker on the doorbell itself not activated, no blue LED turn on around the doorbell button, tried Reolink plugin and ONVIF, both not working, I can't install the older firmware from the Black version it gives error not recognized.
> 
> Any idea anyone can help please? I am thinking to return it since I still have time for return policy but before I return it I want to make sure it doesn't work on White version, I have seen many people says downgrade to older firmware on Black doorbell works, but can't do the same for the White version, I choose this white version because it has taller camera view 3:4 head-to-toe as they say.

Same issue for me, updating the firmware seems to fix it. See https://github.com/koush/scrypted/issues/1376#issuecomment-2253652397
