### ISSUE TITLE
Client error on /addons/xxxxxxxx_scrypted/changelog

### ISSUE THREAD

**Issue by kksligh** [koush/scrypted#1458]
**Describe the bug**
A clear and concise description of what the bug is. The issue tracker is only for reporting bugs in Scrypted, for general support check Discord. Hardrware support requests or assistance requests will be immediately closed.

- I'm getting a recurring error that seems to have started after the last Add On Update
- the error details are as follows...

"ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /addons/XXXXXXXX_scrypted/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.XX.X/addons/XXXXXX_scrypted/changelog')

Source: components/hassio/handler.py:612
integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 10:57:28 AM (63 occurrences)
Last logged: 4:03:51 PM"

**To Reproduce**

- simply start HA-> add on and it happens every 5-10 minutes

**Expected behavior**

- Not throw an error constantly

**Screenshots**

- logs provided - I have nothing else to point to

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu] - 
 - Installation Method: [e.g. Desktop App, Docker, Local]
 - Intel NUC 
- Core 2024.5.0
- Supervisor 2024.04.4
- Operating System 12.2
- Frontend 20240501.0

**Hardware Model (please complete the following information):**
 - Device: [e.g. Amcrest]
 - (4) UVC G4 Instant
 - Connected via [Cloud Key Gen2 Plus] 

**Client (please complete the following information, if applicable):**
 - Software: [e.g. Home app, NVR app, Alexa, Browser]

**Additional context**

**Comment by monsieurlatte** [comment]
I have noticed this as well, however I think it's because .99 was released and then for some reason it was changed back to .98.5 and .99 was not listed as the latest release.  I could be wrong but that is my guess.

**Comment by koush** [comment]
Not enough information. No idea where the error is shown. Probably due to HA update anyways. Would suggest migrating non-add on install in any case.

**Comment by kksligh** [comment]
What do you mean "non-add on install"?  You dont need the add on to use this?

**Comment by kksligh** [comment]
the error is showing in the main HA Logs

**Comment by kksligh** [comment]
I also dont understand closing this as others are seeing the same error - if you can point me to where to pull more logs, I will be glad to trouble shoot or provide any info you may need

**Comment by monsieurlatte** [comment]
The error is in HA because HA is polling the repo for the add on.  Again this showed up after the release was changed from .99 to .98.5.

**Comment by koush** [comment]
> The error is in HA because HA is polling the repo for the add on. Again this showed up after the release was changed from .99 to .98.5.

The release is currently .99. Where are you seeing .98.5?

https://github.com/koush/scrypted/blob/1f2187fd6acefed6ac6aeda0439057c8f61ab62d/install/config.yaml#L3

**Comment by monsieurlatte** [comment]
<img width="1145" alt="Screenshot 2024-05-03 at 2 19 52 PM" src="https://github.com/koush/scrypted/assets/5332785/440d6cf9-bbd3-4bcd-a93d-326defe461fc">

**Comment by koush** [comment]
huh that's weird

**Comment by koush** [comment]
ok that release thing is fixed

**Comment by monsieurlatte** [comment]
Fyi looks like your repo isn't the only one with this issue, have a read here.  https://github.com/home-assistant/core/issues/116470

**Comment by koush** [comment]
> Fyi looks like your repo isn't the only one with this issue, have a read here. [home-assistant/core#116470](https://github.com/home-assistant/core/issues/116470)

yeah that's what I thought...

**Comment by monsieurlatte** [comment]
It's because you don't have changelogs apparently, hopefully HA will fix it so you don't have to.

**Comment by monsieurlatte** [comment]
If you care to fix the bug, apparently supervisor is looking for this file in the root of your repo CHANGELOG.md.

**Comment by monsieurlatte** [comment]
This is the format that MQTT is using and it's working now
`# Changelog

## 6.4.0

- Update mosquitto to 2.0.18

## 6.3.1

- Add ability to use a pre-hashed password for custom logins

## 6.3.0

- Update mosquitto to 2.0.17

## 6.2.1

- Add explicit dependencies for dynamic security plugin and asynchronous name resolver 

## 6.2.0

- Update mosquitto to 2.0.15
- Update libwebsockets to 4.3.2 (fixes Unable to create websockets listener)

## 6.1.3

- Change timestamp format in logs

## 6.1.2

- Add debug option to help with issues

## 6.1.1

- Don't purge openssl in cleanup

## 6.1.0

- Update mosquitto to 2.0.11
- Remove `mosquitto-auth-plug` and replace with `mosquitto-go-auth` 1.8.2
- Change base image from Alpine to Debian (required for `mosquitto-go-auth`)

Note: Mosquitto 2.0.0 did contain some breaking changes. We don't anticipate
most users to be affected by them but if you have a heavily customized mosquitto
config we would advise reviewing [their changelog](https://mosquitto.org/ChangeLog.txt). 

## 6.0.2

- Mention homeassistant and addon users in ACL doc

## 6.0.1

- Fix loading custom mosquitto configuration

## 6.0.0

- Support for anonymous logins has been removed
- Replaced Home Assistant authentication handling
- Merged local account handling with authentication plugin
- Add watchdog endpoint for health monitoring
- Updated mosquitto to 1.6.12
- Updated mosquitto auth plugin to 0.1.5
- Migrate add-on layout to S6 Overlay
- Migrate all script to use Bashio
- Update base image to Alpine Linux 3.13
- Add port descriptions

## 5.1.1

- Update options schema for passwords

## 5.1.0

- Add cafile option in configuration
- Add require_certificate option in configuration

## 5.0.0

- Update mosquitto 1.6.3 / Alpine 3.10
- Migrate to `mosquitto-auth-plug` from pvizeli
- Use auth cache for faster reauthentication

## 4.3.0

- Fix password generator with new images

## 4.2.0

- Enable quiet logging for http auth plugin

## 4.1.0

- Update mosquitto 1.5.6

## 4.0.0

- Use Alpine 3.7 because libwebsocket 3.0.0 is broken on Alpine 3.8`
