### ISSUE TITLE
Cannot renew subscription nor create a new one for NVR

### ISSUE THREAD

**Issue by degudejung** [koush/scrypted#1519]
I recently tested scrypted with the NVR plugin and a quarterly subscription. Therefore I signed up with a randomized Apple iCloud email address and - of course - provided real payment details. Apparently now that subscription did not auto-renew and the plugins complains about not having a valid license. So I tried to log in with the same Email for which I may or may not have the right password (for billing.scrypted.app) and check my payment credentials. 

No.1 The error I see says "Firebase: The password is invalid or the user does not have a password. (auth/wrong-password)." However, I see no option to recover my pw. When next I try the "Create/reset account" it says "Check your inbox to verify your email address." but nothing ever comes in.

No.2 With little bit of frustration and acceptance that I would probably lose my recording history, I tried to sign up for a new account with a different email. When I "Sign in with email", then type email/pw, again it tells me to "Check your inbox to verify your email address." but nothing ever comes in.

No.3 Next I tried to "Retrieve license" from inside the NVR plugin settings it says "Scrypted NVR Licenses were retrieved and can be viewed in the plugin settings." but also "WebAssembly Motion Detection disabled. User not licensed." and "Recording on Cam[..] is inactive. This server requires additional Scrypted NVR Licenses." So I go back to No.1 and...

No.4 Then I tried to change the email in the NVR plugin to create a new account. That however cannot be done, once an email has even been entered there.

No.5 Lastly I tried logging in from another Apple PC with "Log in with Apple". That actually does log me in but then says "This account is not associated with any Scrypted servers. Add invite code".

Ok, now I'm exhausted. I really like the service and I would like to continue paying for it. But I ran out of ideas...

**Comment by koush** [comment]
1. I'd need your email address to look into this. You can also simply sign up with a new address. Your old recording will be retained as long as your drive has space for then.
2. I double checked that email verification works.
3. Would need a valid subscription.
4. Correct. Need to create the account and log in through the billing site. Simply editing it would not work.
5. If Login to apple works, then use that to purchase a new subscription at https://billing.scrypted.app. Then Log into the NVR plugin using that same account. You will similarly need to log into Scrypted Cloud Plugin as well, due to the lost account credentials.

<img width="455" alt="image" src="https://github.com/koush/scrypted/assets/73924/13f0f23e-6740-4cda-90c9-07ec489b41de">

**Comment by koush** [comment]
Let me know if you have further issues. I think the way forward is a new Apple login account, since you lost the previous account, and the email confirmation is failing for you for some unknown reason.
