### ISSUE TITLE
ecobee plugin issue

### ISSUE THREAD

**Issue by revokin** [koush/scrypted#210]
https://github.com/koush/scrypted/blob/4c4cf7d2c4142ff746423907dcb54905f6b371d9/plugins/ecobee/src/main.ts#L554

baseURL: `https://${this.storage.getItem("api_base")}/api/1/`,
This URL appears to no longer be valid.  I was initially unable to connect but resolved the issue by updating the baseURL to:

baseURL: `https://${this.storage.getItem("api_base")}/1/`,

https://www.ecobee.com/home/developer/api/introduction/core-concepts.shtml
This page is where I found the correct URL.

**Comment by koush** [comment]
@billyzoellers

**Comment by koush** [comment]
at first glance your patch seems correct, but I'll let the plugin author chime in before I update the plugin.

**Comment by billyzoellers** [comment]
Thanks @revokin, fixed this in https://github.com/koush/scrypted/pull/212

I wanted to check it out. I have a Bryant HomeWise and the base URL was `https://www.myhome.bryant.com/home/`. For some reason the `/token` and `/authorize` endpoints existed on that base URL, but other requests were `<baseURL>/api/1/<request>`

It looks like my Bryant can just use `api.ecobee.com` instead of the custom base URL - probably better compatibility with ecobee this way too.
