### ISSUE TITLE
[Question] Is there a way to modify a device configuration programmatically?

### ISSUE THREAD

**Issue by poblouin** [koush/scrypted#231]
I looked the documentation and didn't find my answer. Basically, I have a device, a Camera using an RTSP stream. I would like to be able to modify the steam URL because sometimes the IP change (and I can't make it static). Is there a way to do that? E.g. for Homebridge, I could simply modify the `config.json` file, but with Scrypted, I'm struggling to find a way to achieve the same.

Thanks

**Comment by koush** [comment]
`await device.getSettings()`

```json
[
  {
    key: 'username',
    title: 'Username',
    value: 'test',
    description: undefined
  },
  {
    key: 'password',
    title: 'Password',
    value: 'scrypted123',
    type: 'password',
    description: undefined
  },
  {
    key: 'urls',
    title: 'RTSP Stream URL',
    description: 'An RTSP Stream URL provided by the camera.',
    placeholder: 'rtsp://192.168.1.100[:554]/channel/101',
    value: [
      'rtsp://10.10.10.10onvif-media/media.amp?profile=profile2&sessiontimeout=60&streamtype=unicast'
    ],
    multiple: true
  },
]
```

Use `device.putSetting('urls', ['rtsp://whatever'])`

**Comment by EricAndrechek** [comment]
@poblouin Did you ever write a script/automation to do this? If you did would you mind sharing it?

**Comment by poblouin** [comment]
Hi @EricAndrechek! I was not able to achieve what I needed at the time via scrypted, I ended finding a way to make my camera IP static.

**Comment by EricAndrechek** [comment]
Ok as per an idea from @koush from Discord, I instead setup an automation to modify the /etc/hosts file so that the RTSP plugin never notices any differences and doesn't need to rather jankily have its settings modified. I have tested it and can confirm this works and is literally this simple. Documenting it here for anyone else who stumbles across this and needs to have dynamic IPs for their cameras due to networking policies outside of their control. 

Start by picking some hostname, for example, I chose "door-camera" for the camera I have setup watching my apartment's front door peephole. Change whatever IP you had in the RTSP settings to this host, like in this screenshot:
<img width="800" alt="image" src="https://github.com/koush/scrypted/assets/35144594/8d7ecbea-95a6-47f7-a2af-b7b85c375ae3">

Then, create an automation in Scrypted: (I called mine "update camera ips")
<img width="300" alt="image" src="https://github.com/koush/scrypted/assets/35144594/d8430bda-1efb-4ee9-9eae-b52cee5575cf">

Setup the automation trigger however you wish. In my case my apartment tends to redo its network topology and issues new DHCP IP reservations every night around 3AM, so I set this to run every night at 4AM.
<img width="300" alt="image" src="https://github.com/koush/scrypted/assets/35144594/9277b4f0-6e00-43b6-8266-b2ebfb0cf62d">

Then, create a "run shell script" action. I have some example code posted below this for people to copy and paste and modify as they need. In my case, I have a Cloudflare worker that reports the local IP from each Cloudflare tunnel as an API endpoint. So I can query my URL, something like door-camera.example.com/api, and it will return JSON data including the local network IP address that the camera has been issued. 
<img width="300" alt="image" src="https://github.com/koush/scrypted/assets/35144594/973c3904-b8a2-42a7-8f91-22847dd07e02">

Here is the full code I am running in the automation script:
```bash
if ! [ -x "$(command -v jq)" ]; then
  apt-get install -y jq
fi
if ! [ -x "$(command -v ed)" ]; then
  apt-get install -y ed
fi

ipaddr=$(curl -s 'https://door-camera.example.com/api' | jq -r '.ip')
host="door-camera"

matches_in_hosts="$(grep -n $host /etc/hosts | cut -f1 -d:)"
host_entry="${ipaddr} ${host}"

if [ ! -z "$matches_in_hosts" ]
then
  ed -s /etc/hosts << EOF
g/$host/d
w
q
EOF
fi

echo "$host_entry" | tee -a /etc/hosts > /dev/null
```

As this runs in the Scrypted environment, tools like jq for parsing JSON and ed for modifying files in place aren't necessarily included in the original environment, so this script first checks for them and installs them if they don't exist.

Then, we curl the API and parse out the IP address, check if there is an entry for this host in the /etc/hosts file or not, deletes it if there is, and adds the new host and IP. 

Obviously, this is pretty custom-tailored for my specific use-case, but I think the general backbone of the code is there such that people can modify it to fit their needs. 

Also, there are conflicting answers on the internet about whether or not the device immediately receives the changes made in /etc/hosts, or if there are some services that need to be restarted. In my testing, no services needed to be restarted while running this from the Scrypted Home Assistant add-on on a Raspberry Pi 4, but you may have different results.
