### ISSUE TITLE
Mqtt message to trigger doorbell in homekit

### ISSUE THREAD

**Issue by pedroxns** [koush/scrypted#282]
Hello there !
I'm moving from homebridge to home assistant and Scrypted is now an option for my rtsp camera.

I've tryed to follow the "diy doorbell" tutorial but I can't understand how to make scrypted get the mqtt message that my doorbell button sends when pressed and released (on/off).
I've also searched for other issues posted but had no success in find the way.

And at the plugins options everytime i select "doorbell" as device type the homekit integration checkbox disapears.

Can someone give a hand here?
Thanks in advance!

**Comment by koush** [comment]
You need to create a doorbell device group with the camera and the button. Changing the type doesn't work because the camera doesn't have a button. Follow the DIY instructions with a dummy switch to get an understanding of how to create a homekit doorbell from a camera and a dummy button. Once you do that, you can switch to a  mqtt button.
