### ISSUE TITLE
Have just updated to 0.3.3 and now I get the following fatal error: s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by Lukey1979** [koush/scrypted#391]

**Comment by Lukey1979** [comment]
Sorry just to clarify, this is through the Home Assistant Addon

**Comment by giliheriawan** [comment]
i have the same issue and i've tried uninstalling the addon and also restoring backups but nothing works

**Comment by e8link** [comment]
Also having this issue

**Comment by DuncanRae** [comment]
Try installing it again. This issue has been resolved.

**Comment by mdshw5** [comment]
I can confirm that I had the same issue occur today. Re-installing as @DuncanRae suggested did fix the issue for me.

**Comment by Lukey1979** [comment]
I think this is bloody rude of you. If this issue has been fixed then why has it only occurred as of YESTERDAYS update. To just tell us this is closed without any explanation is beyond me. Its NOT fixed. Mine was NEVER broken until the update that was released YESTERDAY. Can you please have a look into this.

**Comment by mdshw5** [comment]
@Lukey1979 i think we’re all having issues with the home assistant add-on. This is the main scrypted repository.

**Comment by mdshw5** [comment]
See here for the HA add-on https://github.com/aegjoyce/ha-addons

**Comment by Lukey1979** [comment]
@mdshw5 Thanks Mate :-) Ill have a look there.

**Comment by aegjoyce** [comment]
> I think this is bloody rude of you. If this issue has been fixed then why has it only occurred as of YESTERDAYS update. To just tell us this is closed without any explanation is beyond me. Its NOT fixed. Mine was NEVER broken until the update that was released YESTERDAY. Can you please have a look into this.

It's been some combination of changes in 0.3.3 and also the way HA now handles add-ons, particularly relating to how the image is loaded and handled. I fixed it this afternoon but it won't appear as an update until the next version of Scrypted is released because of the way the add-on pulls images. Your best bet in the meantime is to roll back to a previous version and then repeat the update process, or backup-uninstall-reinstall.

**Comment by koush** [comment]
> It's been some combination of changes in 0.3.3 and also the way HA now handles add-ons, particularly relating to how the image is loaded and handled. I fixed it this afternoon but it won't appear as an update until the next version of Scrypted is released because of the way the add-on pulls images.

What's the deal with that? Why is it a version behind?

**Comment by aegjoyce** [comment]
It isn’t, it’s pulling 0.3.3. The add-on pulls the latest tagged image from Dockerhub (there’s a script on my GitHub that keeps it up to date). I can’t create a 0.3.3-01 version to push my fixes because the add-on will then try to pull an image tagged 0.3.3-01 (which of course doesn’t exist). So it’s wait for the next version to be released, or roll-back and re-update, or reinstall, in order to pull the changes made today

**Comment by koush** [comment]
I see. I think it may be worth mirroring/copying the docker image to your own docker hub fork (should be fast since it's just a mirror to  an image already on docker hub). Then build off your docker hub mirror, which you can use to tag one off releases to work around this. The Scrypted docker image is fine, there's no reason for me to trigger another update. I'd also like to avoid this downstream dependency requiring me to do a fresh build if there's an error in the downstream build process.

**Comment by aegjoyce** [comment]
> I see. I think it may be worth mirroring/copying the docker image to your own docker hub fork as part of the build process (should be fast since it's just a mirror to an image already on docker hub). Then build off your docker hub mirror, which you can use to tag one off releases to work around this. Or add a way to build one off from a mismatched tag.

Happy to give this a go. I'm not a coder, this was a fudged-together tinkering project mainly designed for my own personal use, I didn't expect to see it getting used so much...

> The Scrypted docker image is fine, there's no reason for me to trigger another update. I'd also like to avoid this downstream dependency requiring me to do a fresh build if there's an error in the downstream build process. This is disruptive to docker users that would receive that as an update.
> 
> Basically the the unofficial HA add-on needs a way to retry the build without me having to push buttons. Similarly, the official docker build supports rebuilding off the same npm tag.

I definitely don't expect you to go changing things on your end to make this add-on work! You do you, and direct any complaints about the add-on over to my repo. I'll try to implement your suggestions to prevent further headaches for you, but give me some time as I have limited experience and ability.
