### ISSUE TITLE
Often receiving "Snapshot Failed" in Home app

### ISSUE THREAD

**Issue by mikesalz** [koush/scrypted#410]
On all of my Arlo cameras and Ring doorbell, I get "Snapshot Failed" nearly every time I open the Home app. It usually resolves itself after some time. Cameras that have had recent motion seem to be more likely to have a snapshot.

I have tried multiple variations of enabling/disabling Snapshots from Prebuffer, as well as changing Snapshot Mode to Never Wait and Timeout. And I do have the snapshot plugin installed. Any suggestions?

![image](https://user-images.githubusercontent.com/46855061/198794136-0d1d5076-e4cf-47b7-85eb-311ba2b9afb9.png)

**Comment by koush** [comment]
it's a cloud stream, so it doesn't maintain a pre buffer or provide recent snapshots.

**Comment by mikesalz** [comment]
Using the HACS aarlo integration for Home Assistant, I do get thumbnails from each of the Arlo cameras.  I know absolutely nothing about HOW it works, but I am wondering if a similar mechanism could pull recent snapshots into Scrypted? 

https://github.com/twrecked/hass-aarlo

**Comment by bjia56** [comment]
@mikesalz Just saw this thread. I'll take a look at aarlo and see if things can be optimized here in the scrypted arlo plugin. Note that since we're dealing with cloud cameras, there will be some amount of latency to fetch the initial snapshot from a cold start. I usually don't tweak the snapshot plugin's settings to timeout or never-wait, but my use case is somewhat different since I don't have homekit.

**Comment by mikesalz** [comment]
Hi @bjia56 - Thanks for chiming in here!  I use Scrypted for Ring and Arlo, and I have noticed that the Ring snapshot is pretty reliably fast and current.  I think that is a cloud camera as well, so maybe some logic can be borrowed from that plugin?  Please let me know if there is anything I can do to help test any changes.  I appreciate your help!

**Comment by mikesalz** [comment]
Hi @bjia56 Just wondering if you have had a chance to look into this yet?  I'm still happy to help test if you need it!

**Comment by bjia56** [comment]
Hey! Unfortunately I haven't looked into this yet, have spent a lot of time
trying to get two way audio working (but unfortunately still running into
issues there). I'll keep you posted and let you know when I start looking
at the snapshots

**Comment by bjia56** [comment]
I took a brief look at the Ring plugin implementation and unfortunately its logic can't be carried over to the Arlo side, since it appears the way the two plugins handle reporting new snapshots back to clients is different - Ring server appears to return pictures as part of the take-picture request, but Arlo requires clients to wait for a download URL to be pushed from the server.

hass-arlo seems to be using a few tricks to warm up the stream first before taking a snapshot - I did take a look a this a while ago and did not have much success with my own cameras (it actually made latency worse). There's also logic there that appears to be caching older snapshots - I'm not sure if it's a good idea to do that in the Scrypted implementation since it'd be serving stale data to the end user.

What Arlo models do you have? Do you happen to have prebuffering manually enabled on your cameras?

**Comment by mikesalz** [comment]
Thank you for doing some research on this!  I have the Arlo Ultra system with 3 cameras connected.  I also have 2 Arlo Baby cameras, but those don't seem to work with Scrypted.  I'm not as concerned about those, though.

When you mention prebuffering, I am guessing you are you referring to these settings?

<img width="605" alt="image" src="https://user-images.githubusercontent.com/46855061/219243271-911ff275-d0bb-4800-80d9-9c7bf52e7200.png">

<img width="597" alt="image" src="https://user-images.githubusercontent.com/46855061/219243072-4bd42724-bca0-4a49-8052-f1297dd9686f.png">

**Comment by bjia56** [comment]
You don't need to enable "Snapshots from Prebuffer" for arlo cameras, the arlo plugin will automatically do so if it detects a stream is in progress

**Comment by mikesalz** [comment]
Thanks @bjia56.  I made that change.
