### ISSUE TITLE
TP-Link Tapo Two Way Audio

### ISSUE THREAD

**Issue by vitva** [koush/scrypted#417]
Hi! Thank you for the great plugin! I would really like to see Two Way Audio for TP-Link Tapo series cameras (support onfiv). It would be great to have such an opportunity

**Comment by Denaun** [comment]
Hi!
Adding some details since I am not sure why this was closed.

While Tapo cameras have ONVIF support, it's only Profile S[^tapo-onvif]. They do have two-way audio, but it's only accessible through their proprietary protocol.

Recently I have discovered [go2rtc](https://github.com/AlexxIT/go2rtc), which is able to expose Tapo cameras through WebRTC **with two-way audio**. \
Sadly, I am not aware of any way of exposing these streams to HomeKit.

Adding support for this in Scrypted would be great.

Thanks!

[^tapo-onvif]: https://www.tapo.com/en/faq/70
