### ISSUE TITLE
Unable to Access GUI

### ISSUE THREAD

**Issue by TransRapid** [koush/scrypted#461]
Used the suggested Docker route. Cannot access the GUI as specified, even when using the IP of the Pi it is running on, as well as from the Pi itself. It seems that the message is part of the script and does not give the true port. A good amount of people on Reddit report the same, but it looks like some comments have been deleted.

**Comment by miwagner1** [comment]
https://github.com/koush/scrypted/wiki/Installation:-Docker-Compose-Linux

Scrypted is now running at: https://localhost:10443/
Note the https.

**Comment by TransRapid** [comment]
Yeah I did…issue was that the docker container doesn’t work right.
Watchtower got a port. Scrypted did not get any port. I just installed it
out of docker. Worked fine doing that.


-- 
Michael Nolhan

**Comment by LanceMcCarthy** [comment]
I can confirm, this is my 4th install attempt and the result is the same. am I supposed to have the scrypted container on port 10443?

![image](https://user-images.githubusercontent.com/3520532/207064879-df6bdc36-2b45-4ace-8685-0c3cc422edf8.png)

**Comment by koush** [comment]
> I can confirm, this is my 4th install attempt and the result is the same. am I supposed to have the scrypted container on port 10443?
> 
> ![image](https://user-images.githubusercontent.com/3520532/207064879-df6bdc36-2b45-4ace-8685-0c3cc422edf8.png)
> 
> I can manually add the port mapping to 10443, but can someone please tell me what the forwarded port should be? Is it 443?

There's no port listed, it should be set up to use host networking. The network interface is shared by the container, no ports passed through.

**Comment by TransRapid** [comment]
So why does Watchtower get a port and not Scrypted? This doesn't make sense that one gets it and not the other. Seems like something is still broken here, at the least the message at the end needs to be removed and replaced with information regarding further instructions and NOT say that it is now available.

**Comment by miwagner1** [comment]
> So why does Watchtower get a port and not Scrypted? This doesn't make sense that one gets it and not the other. Seems like something is still broken here, at the least the message at the end needs to be removed and replaced with information regarding further instructions and NOT say that it is now available.
> 
> Is it possible to automate the end of this install script to use grep to search for the port it is running on and display that instead?

This is why I hate these GUI apps for docker, just confusing to most users who don’t have a technical grasp on containers and networking. You probably have a firewall on that host which is blocking the port.

But why are my other docker services working? Because when you publish ports in docker, it also creates firewall rules on the host by default to open up the port.

You can join the Discord Server https://discord.gg/DcFzmBHYGq and some one may know more about making what setup you currently have running work.

I have tested and ran scrypted without any issues in docker, Kubernetes and podman
(Currently running openSUSE MicroOS + podman + scrypted)

**Comment by koush** [comment]
Host networking is a requirement due to the liberal use of random ports used by homekit accessories. This would require per accessory port forwards in the docker file.
80 and 443 are not freely available ports and will fail to bind in non-root environments. Scrypted should not run as root.

I'm sure you've thought about this much more than I have, do you have other suggestions?
