### ISSUE TITLE
Arlo not loading in scrypted - 403 error

### ISSUE THREAD

**Issue by wnaylor** [koush/scrypted#795]
...
File "/data/scrypted_data/plugins/@scrypted/arlo/python3.9-Linux-x86_64-20230329/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ocapi-app.arlo.com/api/auth?eventId=FE!0e28b423-f93d-4ea8-b518-7db2e3962d00&time=1683711866538
This was not cleared up for me in 0.715 update
[Arlo@Scrypted.pdf](https://github.com/koush/scrypted/files/11479569/Arlo%40Scrypted.pdf)

[Arlo@Scrypted.pdf](https://github.com/koush/scrypted/files/11479577/Arlo%40Scrypted.pdf)

**Comment by bjia56** [comment]
I'm looking into this however it's a bit difficult to troubleshoot since I'm not able to replicate it on my end. My theory is that there was a change on Arlo's side that hasn't rolled out to all geographic regions.

If folks here are in the scrypted Discord and open to helping test possible fixes, please come over to the `#arlo` channel.

**Comment by bjia56** [comment]
Just published out a beta version of the plugin, can folks please try 0.7.18 (or whichever is more recent in the plugin version dropdown, in the event I find issues and publish more versions).

**Comment by fierrogt** [comment]
Hey 0.7.18 fixed for me was having the issue on .15, .16, and .17. Thanks!
