### ISSUE TITLE
Connection interrupted loop - Reolink Duo 2 - Home Assistant Add-on

### ISSUE THREAD

**Issue by rjmcfadd** [koush/scrypted#801]
I keep getting a connection interrupted message when I add the Reolink Duo 2 camera with the ONVIF plugin. I just switched to the Home Assistant add-on and didn't have this problem when I had a docker installation. 

As soon as I add either one of my Duo 2 cameras, I get a connection interrupted message until I either remove the camera or leave the device page on Scrypted. If I then go back into the Duo 2 device page, it happens again.

Any ideas?

**Comment by rjmcfadd** [comment]
I thought that this was solved because after a restart of the computer running Scrypted, it stopped and I was able to add the Duo 2 cameras. However, it is back to the connection interrupted message when going to these cameras.

**Comment by koush** [comment]
probably home assistant ingress issue.

**Comment by Thatbikerdude** [comment]
What was the fix for this? The same thing happens to me now.

**Comment by koush** [comment]
You likely need to clear your HA app cache.

**Comment by lachu2** [comment]
Hi, I've got the same issue - reinstalled plugins and whole scrypted as well and it didn't help. Is there some fix? Thanks!

**Comment by Gustovier** [comment]
I also have the same problem.

**Comment by Slabonski** [comment]
I had this exact same thing happen when adding a Duo 2 camera to either the ONVIF or Reolink plugins while running on HAOS. The problem (as I see it) is caused by the size of the snapshot from the Duo 2. There are two workarounds to this. The first is to change the Clear Stream resolution on the camera from 4608x1728 to 4096x1536. The other is to add a snapshot url which includes width and height parameters. The syntax is: http://(ip address)/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=(password)&width=1536&height=576 make sure the camera is disconnected from the network so you can get back into the plugin to add the snapshot url. Both of these worked in my situation. BTW I determined this by messing with the snapshot url in the RTSP plugin. The RTSP plugin did not present this same problem until I used a snapshot url without width and height constraints.

**Comment by mski363** [comment]
Mate!! Thank you - working like a charm after I followed your snapshot direction, changed all streams to substream & turned on my device VPN.  The VPN was a pita to faultfind :D
