### ISSUE TITLE
Transcode settings for rebroadcast streams

### ISSUE THREAD

**Issue by Janrupf** [koush/scrypted#906]
Applying transcode settings does not effect streams using rebroadcast.

Example:
Set "Video Filter Arguments" to `transpose=0` and select all streams in the "Transcode Streams" dropdown.

Expected behavior:
Stream is rotated when viewing in browser and when streaming using rebroadcast (ffplay for example).

Actual behavior:
Stream is only rotated in browser but not when using ffplay.

**Comment by koush** [comment]
did you try using `npx scrypted ffplay`?

using ffplay by itself will not work, since rebroadcast itself doesn't apply video filters. it provides the video filters down stream.

If you need to apply video filters to apply on the stream ingested by rebroadcast, use the ffmpeg parser and and set the output arguments accordingly. this means it will be a continual transcode.

**Comment by Janrupf** [comment]
Thanks a bunch, using the ffmpeg parser with options did what I wanted it to do. I personally think the settings are slightly confusing (I'd have expected the rebroadcasted streams to have those settings applied), but I see why it works the way it does. Maybe this can be somehow managed in the docs or directly within the settings?
